(() => {
const shell=document.createElement('div');
shell.id='legacy-screen';
document.body.prepend(shell);
for(const selector of ['header','#nav','.bar','#app','footer'])shell.append(document.querySelector(selector));
const initialRender=render;
const initialMonitor=monitor;
const legacyEscape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const sampleActivities=[['大地指纹音乐会','毕节市 · 大方县','09-29 19:30','音乐演出'],['城市阅读分享会','贵阳市 · 城市书房','09-30 14:00','公共文化'],['金秋非遗文化展','黔东南州 · 展示中心','10-01 10:00','非遗展示']];
const more=(title,key,body)=>`<section class="panel"><h2>${title}<button class="legacy-more" data-legacy="${key}" aria-label="${title}详情">更多 ›</button></h2>${body}</section>`;
const caption=text=>`<p class="legacy-note">${text}</p>`;
const sampleScope=()=>state.area==='全省'?1.8:state.area==='贵阳市'?1:.6;
alertRows=function(){const filter=state.tab.alert||0;return table(['影响地区','类型','级别','操作'],alerts.filter((_,index)=>!filter||index===filter-1).map(row=>[row[0],row[1],`<span class="badge ${row[2]==='红色'?'red':''}">${row[2]}</span>`,`<button data-alert="${row[0]}">${state.legacyRecord?.name===row[0]?'已处置':'查看'}</button>`]));};
function flowNumbers(){return `<div class="legacy-six">${[['本年累计接待',28959.29],['本月累计接待',2983.73],['昨日累计接待',107.01],['上季累计接待',9669.61],['上月累计接待',4178.54],['上周累计接待',780.09]].map(([label,value])=>kpi(label,fmt(value*sampleScope()),'万人次')).join('')}</div>`;}
function profile(){return `<div class="legacy-profile"><h3>客流画像</h3><div class="legend">20–30 岁　20 岁以下　30–45 岁　45–60 岁　60 岁以上</div><div class="age">${[21,2,38,32,7].map((value,index)=>`<span style="width:${value}%;background:${['#42a8dc','#929de9','#65ca77','#c6a84e','#ae8ace'][index]}">${value}%</span>`).join('')}</div><div class="legend">女性 40%　 /　 男性 60%</div><div class="age"><span style="width:40%;background:#df936f">40%</span><span style="width:60%;background:#3acbc3">60%</span></div></div>`;}
function sourceRanks(){const groups=[['贵阳市','遵义市','毕节市','黔东南州'],['四川省','广东省','湖南省','江苏省'],['成都市','广州市','长沙市','重庆市']];return `<h3>游客来源汇总</h3>${tabs('source',['省内城市','省份','城市'])}${rankings(groups[state.tab.source||0],'source')}`;}
function mapStage(options=''){return `<div class="legacy-map-stage">${options?`<div class="legacy-map-tools">${options}</div>`:''}${map()}</div>`;}
function resourceSummary(){return `<div class="resource">${[['A级景区','47'],['星级酒店','62'],['等级民宿','37'],['旅游度假区','35'],['乡村旅游点','33']].map(([name,value])=>`<button data-detail="${name}"><small>${name}</small><b>${value}</b></button>`).join('')}</div>${caption('已核实名录：贵阳贵安景区 47 处 / 酒店 62 家；民宿 / 度假区 / 乡村旅游点为模拟名录数量。')}`;}
overview=function(){return `<div class="grid legacy-overview"><div class="col">${more('客流分析','flow',flowNumbers()+sourceRanks()+profile()+caption('客流及画像为演示数据 · 不代表实时监测'))}${more('旅游接待','reception',tabs('reception',['景区接待','住宿接待','团队接待'])+chart('reception').replace('class="chart"','class="chart legacy-reception-chart" preserveAspectRatio="none"').replace('0 0 480 160','0 0 460 160'))}</div><div class="col">${more('重点旅游资源情况','resources',resourceSummary())}${mapStage('<button data-legacy="monitors">重点景区监控</button><button data-legacy="activities">重点活动</button>')}${more('法定节假日数据','holiday',tabs('holiday',['元旦','春节','清明','劳动','端午','中秋','国庆'])+`<div class="legacy-holiday"><div>${kpi('接待游客',n(349.03+(state.tab.holiday||0)*51.6),'万人次')}${kpi('旅游消费金额',n(23.22+(state.tab.holiday||0)*3.8),'亿元')}</div>${table(['排名','景区名称','接待游客'],['黔灵山公园','青岩古镇','天河潭景区'].map((name,index)=>[index+1,`<button data-detail="${name}">${name}</button>`,n(15.8-index*3.4)+' 万人次']))}</div>`)}</div><div class="col">${more('文旅消费情况','consumption',`<div class="metric-grid">${kpi(state.period+'旅游总消费额',n(1968.78),'亿元')}${kpi('人均旅游消费','671.79','元')}</div>${consumption()}${chart('consume',true)}<h3>消费画像</h3><div class="legacy-donut"><div class="ring"></div><div><p>18–35 岁　38%</p><p>36–45 岁　32%</p><p>46 岁以上　30%</p></div></div><h3>夜间消费</h3><div class="metric-grid">${kpi('夜间消费总额',n(802.99),'亿元')}${kpi('夜间人均消费','854.78','元')}</div>${caption('消费为演示数据 · 六业入口及专题页保留')}`)}</div></div>`;};
analysis=function(){return `<div class="grid legacy-analysis"><div class="col">${more('客流变化分析','flow',tabs('flow',['月度','节假日'])+chart('flow')+`<div class="metric-grid">${kpi('累计接待',n(28959.29),'万人次')}${kpi('同比增速','+12.4%','演示')}</div><div class="summary">客流整体呈现季节性波动，暑期与节假日形成接待高峰。点击更多查看分期明细。</div>`)}${more('客源变化分析','origin',tabs('origin',['省份','城市'])+rankings(state.tab.origin?['成都市','广州市','长沙市','重庆市']:['四川省','广东省','湖南省','江苏省'],'origin')+`<div class="summary">核心客源以周边省市及重点城市为主。省内、省外口径分别统计。</div>`)}</div><div class="col">${mapStage()}<div class="legacy-scale"><span>客流环比下降</span><i></i><span>客流环比上升</span></div>${more('智能研判','insight',`<p class="legacy-note">你可以尝试问我：</p><div class="legacy-questions"><button data-question="flow">客流为什么增长？</button><button data-question="spend">哪些行业消费更活跃？</button><button data-question="risk">当前有哪些风险？</button></div><div class="summary" id="insight">点击问题查看原型研判摘要，研判基于模拟场景。</div>`)}</div><div class="col">${more('消费变化分析','consumption',tabs('comparison',['累计消费趋势','行业差值对比'])+chart('comparison',!!state.tab.comparison)+consumption())}${more('夜间消费差值瀑布图','night',chart('night',true)+`<div class="summary">旅游消费随假期和活动安排变化。夜间消费与总体消费分别观察，不重复加总。</div>`)}</div></div>`;};
emergency=function(){return `<div class="grid legacy-emergency"><div class="col">${more('天气预警','weather',`<div class="status"><b>${alerts.length}</b> 条示例预警　<span class="badge red">1 个高风险区域</span></div>${tabs('alert',['全部','红色','橙色','黄色','蓝色'])}${alertRows()}${caption('点击查看预警详情、关联资源及模拟处置。')}`)}${more('重点景区客流预警','capacity',table(['景区','预测峰值 / 人','实时客流 / 人'],[['黔灵山公园','12,815','6,399'],['青岩古镇','5,212','2,339'],['天河潭','2,292','1,967'],['时光贵州','5,510','1,559'],['修文野生动物园','840','57'],['息烽集中营','196','19']].map(row=>[`<button data-detail="${row[0]}">${row[0]}</button>`,row[1],row[2]]))+caption('预测值和实时值均为演示 · 不代表真实预警'))}</div><div class="col"><div class="kpis">${kpi('本年累计预警','2,488','个 · 演示')}${kpi('今日预警',alerts.length,'个 · 示例')}${kpi('高风险区域','1','个 · 示例')}</div>${mapStage()}<div class="legacy-scale"><span>风险等级　低</span><i></i><span>高</span></div>${more('处置记录','records',`<div class="summary">${state.resolved?'已完成模拟处置，请在记录详情中查看。':'尚未处置演示预警，点击左侧预警进入二级调度台。'}</div>`)}</div><div class="col">${more('应急响应主体搜索','responders',`<input id="search" aria-label="响应主体搜索" placeholder="请输入主体名称 / 联系人"><div id="search-result" class="summary">搜索景区、交警或文旅应急中心。</div>`)}${more('重点景区实时监控','monitors',initialMonitor()+`<div class="summary">真实视频待接入 · 点击画面打开监控详情。</div>`)}</div></div>`;};
function legacyDialog(key){
const title={flow:'客流变化分析',reception:'旅游接待明细',origin:'客源变化分析',holiday:'法定节假日数据',consumption:'文旅消费分析',night:'夜间消费明细',insight:'智能研判',weather:'天气预警名录',capacity:'重点景区承载明细',responders:'应急响应主体名录',monitors:'重点景区监控',activities:'重点活动',records:'模拟处置记录'}[key]||'指标详情';
let body='';
if(key==='monitors')body=`<div class="legacy-video-list">${['青岩古镇','天河潭','花溪湿地公园','黔灵山公园','甲秀楼','桃源河','青云市集','省图书馆','红飘带'].map(name=>`<button data-monitor="${name}" class="monitor"><span>视频未接入</span><strong>${name} · 打开详情 ↗</strong></button>`).join('')}</div>`;
else if(key==='activities')body=table(['活动名称','举办地点','场次时间','类型','操作'],sampleActivities.map((row,index)=>[...row,`<button data-legacy-activity="${index}">查看场次 →</button>`]))+caption('名称与排期为交互示例，不代表真实活动安排。');
else if(key==='responders')body=`<input id="legacy-unit-search" aria-label="筛选响应主体" placeholder="输入景区、交警、文旅关键词"><div id="legacy-units"></div>`;
else if(key==='weather')body=table(['影响地区','类型','级别','开始时间','操作'],alerts.map(row=>[row[0],row[1],row[2],row[3],`<button data-alert="${row[0]}">进入模拟调度</button>`]));
else if(key==='records')body=state.resolved?table(['事件','响应单位','备注','状态'],[[legacyEscape(state.legacyRecord?.name||'预警事件'),legacyEscape(state.legacyRecord?.unit||'属地文旅应急中心'),legacyEscape(state.legacyRecord?.memo||'无补充备注'),'已模拟处置']]):'<div class="summary">暂无模拟处置记录。可从天气预警列表进入调度台。</div>';
else if(key==='capacity')body=table(['景区','实时人数 / 人','瞬时上限 / 人','承载率','状态'],[['黔灵山公园',6399,120000,'5.33%','示例舒适'],['青岩古镇',2339,45000,'5.20%','示例舒适'],['天河潭',1967,50000,'3.93%','示例舒适']]);
else if(key==='insight')body=`<div class="summary"><h3>${state.area} · 演示研判</h3>客流、客源和消费需采用一致地域及时间范围。高风险预警应回到应急指挥页面核验。这里展示固定演示摘要，未连接实际智能研判服务。</div>`;
else {const consumptionView=['consumption','night'].includes(key);body=`<div class="metric-grid">${kpi('当前范围',state.area,'')}${kpi('当前周期',state.period,'')}</div>${chart(consumptionView?'comparison':'flow',consumptionView)}${table(['序号',key==='origin'?'客源地':'统计分期',consumptionView?'消费金额 / 亿元':'接待 / 万人次','说明'],Array.from({length:6},(_,index)=>[index+1,key==='origin'?['四川省','广东省','湖南省','江苏省','重庆市','云南省'][index]:`${index+1} ${state.period==='昨日'?'时段':state.period==='本月'?'旬内分段':'月'}`,n((consumptionView?26.4:385.2)*(index+1)),'原型演示']))}${caption('分期数据为示例，正式口径与来源待业务接入。')}`;}
dialog(title+' · 二级详情',`<div class="legacy-detail-bar"><span>${state.area} / ${state.period}</span><button data-legacy-back>← 返回大屏</button></div>${body}`);
document.querySelector('#dlg').classList.add('legacy-detail');
bindDetail();
if(key==='responders'){
const fillUnits=()=>{const query=document.querySelector('#legacy-unit-search').value.trim();const names=['贵阳市景区管理中心','贵阳市交警指挥中心','息烽县文旅应急中心'];document.querySelector('#legacy-units').innerHTML=table(['响应主体','接入状态','操作'],names.filter(name=>name.includes(query)).map(name=>[name,'示例单位',`<button data-alert="${name}">模拟调度</button>`]));bindDetail();};
document.querySelector('#legacy-unit-search').oninput=fillUnits;fillUnits();
}
}
function bindDetail(){
document.querySelectorAll('#dlg [data-legacy-back]').forEach(button=>button.onclick=()=>document.querySelector('#dlg').close());
document.querySelectorAll('#dlg [data-alert]').forEach(button=>button.onclick=()=>showAlert(button.dataset.alert));
document.querySelectorAll('#dlg [data-monitor]').forEach(button=>button.onclick=()=>dialog(button.dataset.monitor+' · 监控详情',`<button data-legacy="monitors">← 返回监控列表</button><div class="video">▣ ${button.dataset.monitor}<br>视频未接入</div>${caption('预留视频点位、采集时间、在线状态。当前不展示虚构监控画面。')}`));
document.querySelectorAll('#dlg [data-legacy-activity]').forEach(button=>button.onclick=()=>{const row=sampleActivities[Number(button.dataset.legacyActivity)];dialog(row[0]+' · 场次详情',`<button data-legacy="activities">← 返回活动列表</button><div class="summary">${row[1]} · ${row[2]} · 示例排期</div>${table(['场次','投放票量 / 张','已售 / 张','剩余 / 张','核验'],[['第 1 场',5000,3860,1140,'待开场'],['第 2 场',3000,1960,1040,'待开场']])}${caption('票务为演示数据。未开场的核验数据不以零代替。')}`);});
}
showAlert=function(name){const row=alerts.find(item=>item[0]===name);dialog(name+' · 应急调度',`<div class="legacy-detail-bar"><button data-legacy="weather">← 预警列表</button><span class="badge red">${row?row[1]+' / '+row[2]:'应急响应'} · 演示</span></div><div class="details"><div><small>影响区域</small>${legacyEscape(name)}</div><div><small>关联资源</small>3 个示例重点资源</div></div><label class="legacy-form">响应主体<select id="unit"><option>属地文旅应急中心</option><option>景区管理处</option><option>交警指挥中心</option></select></label><textarea id="memo" aria-label="处置备注" placeholder="填写处置备注（选填）"></textarea>${caption('模拟操作仅保存在本页面，不向任何外部单位发送指令。')}<div class="actions"><button id="resolve">确认模拟处置</button></div>`);document.querySelector('#dlg').classList.add('legacy-detail');document.querySelector('#resolve').onclick=()=>{state.resolved=true;state.legacyRecord={name,unit:document.querySelector('#unit').value,memo:document.querySelector('#memo').value};document.querySelector('#dlg').close();render();toast('已保存模拟处置记录');};};
document.addEventListener('click',event=>{const button=event.target.closest('[data-legacy]');if(!button)return;if(button.dataset.legacy==='resources'){document.querySelector('[data-detail="A级景区"]')?.click();return;}legacyDialog(button.dataset.legacy);});
render=function(){initialRender();shell.dataset.page=state.page;};
function fit(){const scale=Math.min(innerWidth/1920,innerHeight/1080);document.documentElement.style.setProperty('--legacy-scale',scale);if(typeof boundaryMap!=='undefined'&&boundaryMap)boundaryMap.invalidateSize();}
window.addEventListener('resize',fit);
fit();render();
})();
