(() => {
const root=document.querySelector('#screen'),modal=document.querySelector('#metric-dialog');
const districts=['南明区','云岩区','花溪区','乌当区','白云区','观山湖区','开阳县','息烽县','修文县','清镇市','贵安新区','双龙航空港经济区','高新区'];
const groups={culture:[['公共文化设施',[1,2,3]],['三馆服务效能',[4,5,6]],['惠民服务与覆盖',[7,8,9]],['文化活动供给',[10,11]],['非遗保护与活化',[13,14,15,16]],['文化成果与文献',[12,17]]],tourism:[['旅游运行总览',[17,18]],['景区资源与承载',[1,2,10]],['景区客流与画像',[4,5,6]],['住宿接待',[11,12,13]],['配套交通与监控',[7,8,9,16,30]],['消费运行观察',[19,20,21,22,23,24,25]],['市场主体与服务治理',[14,15,27]],['活动、旅居与产业项目',[26,28,29]]]};
let page=location.hash==='#tourism'?'tourism':'culture',region='全域',period='本月',demo=true,layer='资源分布';
const sheet=()=>page==='culture'?'文化':'旅游';
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const value=(number,stock=false)=>demo?(region==='全域'?Number((number*(stock?1:period==='本年'?8.2:period==='昨日'?.035:1)).toFixed(Number.isInteger(number)?0:1)):regionalValue(number,region,stock)).toLocaleString('zh-CN'):'—';
const fixed=number=>demo?String(number):'—';
const count=category=>window.officialTourismResources.filter(item=>item.category===category&&(region==='全域'||item.area===region)).length;
function panel(title,body,group,extra=''){return `<section class="panel ${extra}"><h2>${title}<button class="module-link" data-group="${group}">查看明细 ↗</button></h2>${body}</section>`;}
function stats(items){return `<div class="mini-stats">${items.map(([name,number,unit])=>`<div><small>${name}</small><b>${['％','%','元'].includes(unit)?fixed(number):value(number,['个','家','人','项','座','㎡','册','件','辆'].includes(unit))} <small style="display:inline">${unit}</small></b></div>`).join('')}</div>`;}
function bars(items,real=false,stock=false){const max=Math.max(1,...items.map(item=>item[1]));return items.map(([name,number],index)=>`<div class="bar-row"><span>${name}</span><div class="bar-track"><i style="width:${real||demo?number/max*100:0}%;opacity:${1-index*.07}"></i></div><b>${real?number:value(number,stock)}</b></div>`).join('');}
function chart(labels=period==='昨日'?['00时','04时','08时','12时','16时','20时','24时']:period==='本年'?['1月','3月','5月','7月','9月','11月','12月']:['01日','05日','10日','15日','20日','25日','30日']){if(!demo)return '<div class="empty-chart">业务数据待接入 · 不以 0 代替缺失</div>';const points=labels.map((label,index)=>`${20+index*62},${90-Math.sin(index*1.6+districts.indexOf(region))*21-index*5}`);return `<svg class="chart" viewBox="0 0 420 145" role="img" aria-label="${region}${period}趋势演示"><path d="M10 30H410 M10 60H410 M10 90H410 M10 120H410" stroke="#2c4b5855" fill="none"/><path d="M${points.join(' L')} L392 122 L20 122Z" fill="#52bfa416"/><polyline points="${points.join(' ')}" fill="none" stroke="var(--accent)" stroke-width="2"/>${points.map(point=>{const [horizontal,vertical]=point.split(',');return `<circle cx="${horizontal}" cy="${vertical}" r="3" fill="var(--accent)"/>`}).join('')}${labels.map((label,index)=>`<text x="${15+index*62}" y="142">${label}</text>`).join('')}</svg>`;}
function item(name,description,number,stock=false){return `<div class="item"><div>${name}<small>${description}</small></div><b>${typeof number==='number'?value(number,stock):number}</b></div>`;}
function header(){return `<header class="masthead"><div class="identity"><small>GUIYANG GUI’AN / ${page==='culture'?'CULTURE':'TOURISM'} OBSERVATORY</small><h1>${page==='culture'?'文化服务与传承大屏':'旅游运行与产业大屏'}</h1></div><nav class="navigation"><a href="#culture" class="${page==='culture'?'active':''}">文化专题</a><a href="#tourism" class="${page==='tourism'?'active':''}">旅游专题</a><a href="index.html#overview">返回综合大屏 ↗</a></nav><div class="dateline">需求方案 · 非实时监测<br>贵阳贵安数智文旅平台</div></header><div class="toolbar"><span class="intro">${page==='culture'?'资源可及 → 服务供给 → 群众参与 → 文化传承':'资源底数 → 游客接待 → 消费转化 → 承载保障 → 行业治理'}</span><label>区域 <select id="region"><option>全域</option>${districts.map(name=>`<option ${name===region?'selected':''}>${name}</option>`).join('')}</select></label><label>统计周期 <select id="period">${['昨日','本月','本年'].map(name=>`<option ${name===period?'selected':''}>${name}</option>`).join('')}</select></label><button id="demo" class="${demo?'active':''}">${demo?'● 演示数据已开启':'仅显示已核实数据'}</button><button id="all-metrics">指标逻辑 / ${window.screenRequirements[sheet()].length} 项</button></div>`;}
function kpis(){const items=page==='culture'?[['公共文化设施',326,'个',0],['累计入馆',185620,'人次',1],['文化活动',428,'场',3],['惠民受益',96800,'人次',2],['非遗代表性项目',153,'项',4],['代表性传承人',216,'人',4]]:[['A级景区',count(0),'处',1,true],['星级酒店',count(1),'家',3,true],['游客接待',386,'万人次',0],['旅游总花费',285640,'万元',0],['过夜游客',126,'万人次',0],['投诉办结率',96.8,'%',6]];return `<section class="kpis">${items.map(([name,number,unit,group,real])=>`<button class="kpi" data-group="${group}" ${real?'data-official="'+(name==='A级景区'?0:1)+'"':''}><span>${name}</span><strong>${real?number:unit==='%'?(demo?'96.8':'—'):value(number,page==='culture'&&[0,4,5].includes(items.findIndex(item=>item[0]===name)))}<small>${unit}</small></strong><em>${real?'官方名录 · 2026年8月':demo?'演示值 · '+(page==='culture'&&[0,4,5].includes(items.findIndex(item=>item[0]===name))?'资源快照':period):'待接入 / 口径待确认'}</em></button>`).join('')}</section>`;}
function regionalValue(number,name,stock=false){
const total=Math.round(number*(stock?1:period==='本年'?8.2:period==='昨日'?.035:1));
const weights=districts.map((_,index)=>10+(index*7)%13),sum=weights.reduce((total,weight)=>total+weight,0);
const index=districts.indexOf(name),before=weights.slice(0,index).reduce((total,weight)=>total+weight,0);
return Math.round(total*(before+weights[index])/sum)-Math.round(total*before/sum);
}
function regionPanel(){
const resources=layer==='资源分布',tourism=page==='tourism',official=tourism&&resources;
const columns=resources?(tourism?['A级景区 / 处','星级酒店 / 家']:['文化设施 / 个','文化活动 / 场']):tourism?['接待游客 / 万人次','旅游花费 / 万元']:['入馆 / 人次','惠民受益 / 人次'];
const totals=resources?(tourism?[47,62]:[326,428]):tourism?[386,285640]:[185620,96800];
const entries=districts.map(name=>({name,values:totals.map((total,index)=>official?window.officialTourismResources.filter(item=>item.category===index&&item.area===name).length:regionalValue(total,name,resources&&index===0))}));
const maximum=Math.max(1,...entries.map(entry=>entry.values[0]));
return `<section class="panel regional-panel"><h2>${tourism?'各区域旅游数据':'各区域文化数据'}<small>点击区域联动 · 再点取消</small></h2><div class="map-tabs">${['资源分布','服务态势'].map(name=>`<button data-layer="${name}" class="${layer===name?'active':''}">${name==='资源分布'?'资源与供给':'运行与成效'}</button>`).join('')}<button id="reset-region">返回全域</button></div><div class="regional-head"><span>统计区域</span><span>${columns[0]}</span><span>${columns[1]}</span></div><div class="regional-rows">${entries.map(entry=>`<button class="regional-row ${region===entry.name?'selected':''}" data-region="${entry.name}" aria-pressed="${region===entry.name}"><span>${entry.name}<i style="width:${official||demo?entry.values[0]/maximum*100:0}%"></i></span><b>${official||demo?entry.values[0].toLocaleString('zh-CN'):'—'}</b><b>${official||demo?entry.values[1].toLocaleString('zh-CN'):'—'}</b></button>`).join('')}</div><div class="regional-summary"><span>${region==='全域'?'全域对比':region+' · 已联动筛选'}</span><span class="tag">${official?'官方名录':demo?'演示数据':'数据待接入'}</span></div><p class="map-note">${official?'按官方名录所属区域统计；贵安、双龙、高新区单列，避免重复归区。':'区域数值为演示分配，非实测统计；资源为快照，运行指标随周期切换。'}</p></section>`;
}


function columns(items,stock=false){const maximum=Math.max(...items.map(entry=>entry[1]),1);return '<div class="comparison-bars">'+items.map(([name,number],index)=>'<div class="comparison-column" style="--tone:'+['#42dccb','#598cff','#efc554'][index%3]+'"><b>'+value(number,stock)+'</b><i style="height:'+(demo?number/maximum*80:0)+'px"></i><span>'+name+'</span></div>').join('')+'</div>';}
function coverage(){return '<div class="coverage-visual">'+[['◇','惠民项目',28],['▥','服务阵地',326],['⌂','覆盖乡镇',86],['▦','覆盖村社',418]].map(([icon,name,number])=>'<div class="coverage-node"><i>'+icon+'</i><div><b>'+value(number,true)+'</b><small>'+name+' / 个</small></div></div>').join('')+'</div>';}
const monitorNames=['黔灵山 · 入园广场','青岩古镇 · 游客通道','天河潭 · 观景区'];
function monitorScene(index){return '<svg class="monitor-scene" viewBox="0 0 480 270" preserveAspectRatio="xMidYMid slice" role="img" aria-label="景区监控示意插画，非实时画面"><rect width="480" height="270" fill="#254e61"/><circle cx="390" cy="48" r="22" fill="#d5d9a077"/><path d="M0 153L58 70L117 127L191 41L285 130L366 65L480 148V270H0Z" fill="#295c61"/><path d="M0 177L96 108L159 153L258 86L341 153L425 117L480 155V270H0Z" fill="#173e49"/>'+ (index===1?'<path d="M50 169h120v73H50zm192-20h145v90H242" fill="#746e61"/><path d="M32 170l77-43 79 43zm190-22l93-49 92 49z" fill="#152d3e"/><path d="M82 240v-49h38v49m163 0v-62h48v62" fill="#1a303b"/>':index===2?'<path d="M80 270Q230 142 480 182V270Z" fill="#328c9d"/><path d="M12 241Q170 177 402 190" fill="none" stroke="#abae91" stroke-width="12"/>':'<path d="M110 270L208 161H275L412 270Z" fill="#768984"/><path d="M180 161v-31h115v31m-134-31h152l-77-32z" fill="#ad9d79"/>')+'<g fill="#0b2836">'+[0,1,2,3,4].map(person=>'<circle cx="'+(160+person*36)+'" cy="'+(213+person%2*12)+'" r="4"/><path d="M'+(160+person*36)+' '+(219+person%2*12)+'v14" stroke="#0b2836" stroke-width="5"/>').join('')+'</g><path d="M12 30V12h30m396 0h30v18M12 240v18h30m396 0h30v-18" fill="none" stroke="#d0faff88"/><text x="18" y="251" fill="#d0faff" font-size="11">CAM 0'+(index+1)+' · DEMO / NOT LIVE</text></svg>';}
function monitors(){return '<div class="monitor-grid">'+monitorNames.map((name,index)=>'<button class="monitor-tile" data-monitor="'+index+'" aria-label="放大'+name+'监控示意">'+monitorScene(index)+'<span class="monitor-badge">● 示意 · 未接入</span><span class="monitor-caption">'+name+' ↗</span></button>').join('')+'</div><p class="graphics-note">三路点位示意 · 点击放大 / 切换 · 非真实监控画面</p>';}
function openMonitor(index){modal.innerHTML='<div class="dialog-head"><h2>'+monitorNames[index]+'</h2><button id="close-detail" aria-label="关闭监控示意">×</button></div><div class="monitor-preview">'+monitorScene(index)+'<span class="monitor-badge">示意画面 · 视频未接入</span></div><p>仅展示点位预览交互，不代表摄像头在线或现场实时状态。</p><div class="monitor-switch">'+monitorNames.map((name,position)=>'<button data-camera="'+position+'" '+(position===index?'class="active"':'')+'>'+name+'</button>').join('')+'</div>';modal.querySelector('#close-detail').onclick=()=>modal.close();modal.querySelectorAll('[data-camera]').forEach(button=>button.onclick=()=>openMonitor(Number(button.dataset.camera)));if(!modal.open)modal.showModal();}


const graphPalette=['#44ddc2','#5791ff','#f3ca65','#b096e5'];
function distribution(items,title,official=false,pie=false){
  if(!demo&&!official)return '<div class="empty-chart">结构数据待接入</div>';
  const total=items.reduce((sum,entry)=>sum+entry[1],0);
  if(!total)return '<div class="empty-chart">当前区域暂无名录记录</div>';
  let cursor=0;
  const stops=items.map((entry,index)=>{const left=cursor;cursor+=entry[1]/total*100;return graphPalette[index%4]+' '+left+'% '+cursor+'%';}).join(',');
  return '<div class="topic-distribution"><div class="topic-wheel '+(pie?'topic-pie':'')+'" style="--segments:conic-gradient('+stops+')" role="img" aria-label="'+escape(title)+'"><span>'+escape(title)+'</span></div><div class="topic-chart-key">'+items.map(([name,number],index)=>'<div><i style="background:'+graphPalette[index%4]+'"></i><span>'+escape(name)+'</span><b>'+(number/total*100).toFixed(1)+'%</b></div>').join('')+'</div></div>';
}
function percentBars(items,title){
  if(!demo)return '<div class="empty-chart">比例数据待接入</div>';
  const total=items.reduce((sum,entry)=>sum+entry[1],0);
  return '<div class="topic-percent"><small>'+title+'</small><div class="topic-percent-stack">'+items.map(([name,number],index)=>'<i title="'+name+' '+(number/total*100).toFixed(1)+'%" style="width:'+number/total*100+'%;background:'+graphPalette[index%4]+'">'+(number/total*100).toFixed(0)+'%</i>').join('')+'</div><div class="topic-percent-key">'+items.map(([name],index)=>'<span><i style="background:'+graphPalette[index%4]+'"></i>'+name+'</span>').join('')+'</div></div>';
}
function gauge(number,title){
  return '<div class="topic-gauge" style="--percent:'+(demo?number:0)+'"><div><b>'+(demo?number+'%':'—')+'</b><span>'+title+'</span></div></div>';
}

function culture(){return `<div class="layout"><div class="column">${panel('公共文化设施',distribution([['图书馆',28],['文化馆',16],['博物馆',32],['其他阵地',250]],'设施类型',false,true)+stats([['建筑面积',182600,'㎡'],['服务面积',124800,'㎡'],['活动面积',86200,'㎡']])+'<p>设施数量与面积分开统计 · 点击查看类型及等级口径</p>',0)}${panel('三馆服务效能',columns([['市图书馆',82600],['少儿图书馆',58420],['市群艺馆',44600]])+percentBars([['市图书馆',82600],['少儿图书馆',58420],['市群艺馆',44600]],'三馆入馆人次构成')+'<p>趋势为累计入馆人次；实时在馆人数另列，不混加。</p>',1)}</div><div class="column">${regionPanel()}${panel('文化活动供给',stats([['营业性演出',86,'场'],['公益活动',342,'场'],['参与人数',128600,'人次']])+percentBars([['营业性演出',86],['公益活动',342]],'活动场次构成')+chart()+'<div class="legend"><span><i></i>活动场次趋势 · 演示</span></div>',3)}</div><div class="column">${panel('非遗保护与活化',`<div class="ring-layout">${demo?'<div class="ring"></div>':'<div class="empty-chart">等级分布待接入</div>'}<div class="ring-labels">${item('国家级','项目等级',18,true)}${item('省级','项目等级',63,true)}${item('市级及其他','项目等级',72,true)}</div></div>`+stats([['展示场所',42,'个'],['非遗活动',36,'场'],['参与人次',12600,'人次']]),4)}${panel('惠民服务与覆盖',coverage()+'<p>受益人次不等于服务人口；缺少总体分母时只呈现覆盖数量。</p>',2)}</div></div><div class="bottom-grid">${panel('文化成果与荣誉',item('年度成果与荣誉','名称 · 授予单位 · 获得时间',24,true)+'<p>点击指标详情查看成果台账设计；实际荣誉内容待填报。</p>',5)}${panel('生态文明图书与文献',stats([['图书资源',12680,'册'],['文献资源',426,'件'],['收藏单位',18,'家']])+'<p>册、件分别计量，收藏单位为建议派生维度。</p>',5)}</div>`;}
function tourism(){const scenic=window.officialTourismResources.filter(item=>item.category===0&&(region==='全域'||item.area===region));return `<div class="layout"><div class="column">${panel('游客接待与消费',percentBars([['过夜游客',126],['一日游游客',260]],'接待结构 / 同周期人数占比')+chart()+'<p>旅游总花费与接待人次使用同一统计周期、同一地域口径。</p>',0)}${panel('景区客流与画像',stats([['入园人数',128600,'人次'],['出园人数',121800,'人次'],['实时在园',6800,'人']])+distribution([['省内',62],['省外',35],['其他',3]],'客源占比')+percentBars([['18—29岁',32],['30—44岁',38],['45岁及以上',30]],'游客年龄结构'),2)}${panel('交通及配套保障',stats([['剩余车位',1860,'个'],['观光车辆',126,'辆'],['旅游厕所',286,'座']])+'<p>交通方式涵盖铁路、机场、公交、地铁等；客流不加总为游客量。</p>',4)}</div><div class="column">${regionPanel()}${panel('景区资源与承载',distribution(['AAAAA','AAAA','AAA','AA'].map(grade=>[grade+'级',scenic.filter(item=>item.grade===grade).length]),'景区等级',true)+'<div class="legend"><span class="tag">官方名录快照</span><span>等级分布合计 '+scenic.length+' 处</span></div>'+item('实时承载 / 开放状态','需接入瞬时承载量与实时在园人数','待接入'),1)}</div><div class="column">${panel('住宿接待与经营','<div class="topic-occupancy">'+gauge(72,'客房入住率')+stats([['入住人数',96800,'人次'],['平均房价',386,'元']])+'</div>'+percentBars([['省内客源',42],['省外客源',58]],'住宿客源结构')+'<p>星级酒店名录不等同于全量住宿企业。房量与经营数据另行接入。</p>',3)}${panel('消费运行观察',columns([['餐饮',86500],['商圈',62400],['老字号',12600]])+'<p>营业额 · 万元 / 演示，同地域同周期对比。</p>',5)}${panel('景区监控',monitors(),4)}</div></div><div class="bottom-grid">${panel('市场主体与服务治理',stats([['旅行社',286,'家'],['持证导游',4620,'人'],['受理投诉',126,'件']])+'<p>投诉办结率按同批受理事项统计；执法案件单独列示。</p>',6)}${panel('活动与旅居',item('重要文旅活动','计划 / 实际场次 / 参与人数',68)+item('旅居资源点','业态与接待口径待处室确认',42,true),7)}${panel('产业项目推进','<div class="timeline"><div>储备<b>'+value(36,true)+'</b>项</div><div>在建<b>'+value(18,true)+'</b>项</div><div>投产<b>'+value(12,true)+'</b>项</div></div><p>投资额与建设进度分开统计，阶段互斥去重。</p>',7)}</div>`;}
function requirementDetail(groupIndex){const source=window.screenRequirements[sheet()],group=groups[page][groupIndex],records=group?source.filter(metric=>group[1].includes(metric.id)):source;modal.innerHTML=`<div class="dialog-head"><h2>${group?group[0]:sheet()+'指标逻辑与来源'}</h2><button id="close-detail" aria-label="关闭指标详情">×</button></div><p>${region} / ${period} · 原表为需求确认表，尚无实测值。以下为建议展示方案，待业务确认。</p><div class="metric-list">${records.map(metric=>`<section class="metric-record"><h3>${String(metric.id).padStart(2,'0')} ${escape(metric.name)}</h3><dl>${[['原表位置',sheet()+'!D'+metric.row],['责任部门',metric.owner],['展示字段',metric.fields],['维度与单位',metric.dimensions+' · '+metric.unit],['拟定来源',metric.source],['采集方式',metric.method],['更新频率',metric.frequency],['确认状态',metric.status],['上屏选择',metric.display||'原表未勾选；本页为设计建议']].map(([label,content])=>`<dt>${label}</dt><dd>${escape(content)}</dd>`).join('')}</dl></section>`).join('')}</div>`;modal.querySelector('#close-detail').onclick=()=>modal.close();modal.showModal();}
function official(category){const records=window.officialTourismResources.filter(item=>item.category===category&&(region==='全域'||item.area===region));modal.innerHTML=`<div class="dialog-head"><h2>${category===0?'A级景区':'星级酒店'} · ${region} · ${records.length} ${category===0?'处':'家'}</h2><button id="close-detail">关闭</button></div><p>官方名录：2026年8月公布。当前资源数量不随统计周期换算。</p><div class="metric-list">${records.map(item=>`<section class="metric-record"><h3>${escape(item.name)}</h3>${escape(item.area)} / ${escape(item.grade)}<p>${escape(item.address)}</p><a href="${item.source}" target="_blank" rel="noopener noreferrer">查看官方来源 ↗</a></section>`).join('')||'<p>当前区域没有该类名录记录。</p>'}</div>`;modal.querySelector('#close-detail').onclick=()=>modal.close();modal.showModal();}

function render(){document.body.className=page;root.innerHTML=`<main class="shell">${header()}${kpis()}${page==='culture'?culture():tourism()}<footer class="footer"><span>${demo?'● 设计演示：除明确标注的官方名录外，所有业务数值均为模拟数据。':'● 核实模式：未接入指标以 — 显示；不代表数值为零。'}<br>原表：文化17项 / 旅游30项 · 统计周期只作用于流量指标，资源存量按最新快照展示。</span><button class="source-button" id="logic">查看完整指标映射与口径说明 ↗</button></footer></main>`;document.querySelectorAll('[data-monitor]').forEach(button=>button.onclick=()=>openMonitor(Number(button.dataset.monitor)));document.querySelector('#region').onchange=event=>{region=event.target.value;render();};document.querySelector('#period').onchange=event=>{period=event.target.value;render();};document.querySelector('#demo').onclick=()=>{demo=!demo;render();};document.querySelector('#all-metrics').onclick=()=>requirementDetail();document.querySelector('#logic').onclick=()=>window.open('大屏指标设计说明.md','_blank');document.querySelectorAll('[data-group]').forEach(button=>button.onclick=()=>button.hasAttribute('data-official')?official(Number(button.dataset.official)):detail(Number(button.dataset.group)));document.querySelectorAll('[data-layer]').forEach(button=>button.onclick=()=>{layer=button.dataset.layer;render();});document.querySelector('#reset-region').onclick=()=>{region='全域';render();};document.querySelectorAll('[data-region]').forEach(button=>button.onclick=()=>{region=region===button.dataset.region?'全域':button.dataset.region;render();});}
function detail(groupIndex, metricId, search = '') {
  const group = groups[page][groupIndex];
  const metrics = window.screenRequirements[sheet()].filter(metric => group[1].includes(metric.id));
  const metric = metrics.find(entry => entry.id === metricId) || metrics[0];
  const dataset = window.topicDetailData(sheet(), metric, {region, period, demo});
  const records = dataset.rows.filter(row => row.some(cell => String(cell).includes(search)));
  modal.innerHTML = `<div class="dialog-head"><div><small>GUIYANG · ${dataset.official?'OFFICIAL DIRECTORY':'BUSINESS DETAIL'}</small><h2>${group[0]}</h2></div><button id="close-detail" aria-label="关闭业务详情">×</button></div><div class="topic-detail-scope"><span>${region==='全域'?'贵阳贵安 · 全域':escape(region)} / ${period}</span><span class="tag">${dataset.official?'官方名录 · 未公开字段待接入':demo?'模拟明细 · 非完整汇总台账':'业务数据待接入'}</span></div><nav class="topic-detail-tabs">${metrics.map(entry=>`<button data-detail-metric="${entry.id}" aria-pressed="${entry.id===metric.id}">${escape(entry.name)}</button>`).join('')}</nav><form class="topic-detail-search"><label>搜索明细 <input name="search" placeholder="名称、地区或类型" value="${escape(search)}"></label><button>查询</button><button type="button" data-detail-reset>重置</button><span>共 ${records.length} 条${dataset.official?'':'示例记录'}</span></form><div class="topic-detail-table"><table><thead><tr>${dataset.fields.map(field=>`<th>${escape(field)}</th>`).join('')}</tr></thead><tbody>${records.map(row=>`<tr>${row.map(cell=>`<td>${escape(cell)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${dataset.fields.length}">${search?'没有匹配记录，请调整搜索。':'暂无已接入明细，可切换演示模式查看样式。'}</td></tr>`}</tbody></table></div><details class="topic-field-note"><summary>字段来源与统计口径</summary><p>${escape(metric.fields)}</p><p>${escape(metric.dimensions)} · ${escape(metric.unit)} / ${escape(metric.frequency)}</p><p>${dataset.official?'部分字段来自现有官方名录，其余显示待接入。':'演示明细仅展示填报形式，不用于反推主屏总量；数量和面积等不同单位独立展示。'} 原表：${sheet()}!D${metric.row}</p></details>`;
  modal.querySelector('#close-detail').onclick=()=>modal.close();
  modal.querySelectorAll('[data-detail-metric]').forEach(button=>button.onclick=()=>detail(groupIndex,Number(button.dataset.detailMetric)));
  modal.querySelector('form').onsubmit=event=>{event.preventDefault();detail(groupIndex,metric.id,new FormData(event.currentTarget).get('search').trim());};
  modal.querySelector('[data-detail-reset]').onclick=()=>detail(groupIndex,metric.id);
  if(!modal.open)modal.showModal();
}
function fitTopics(){document.documentElement.style.setProperty('--topic-scale',Math.min(window.innerWidth/1920,window.innerHeight/1080));}
window.addEventListener('resize',fitTopics);
window.addEventListener('hashchange',()=>{page=location.hash==='#tourism'?'tourism':'culture';region='全域';render();});fitTopics();render();
})();
